kingdoms:
    nederland: 0
    belgie: 0
    ijsland: 0
    zweden: 0
    duitsland: 0
    monaco: 0
    italie: 0
    rusland: 0
    spanje: 0
    kosovo: 0
    turkije: 0
    zwitserland: 0
    engeland: 0
    cyprus: 0
    frankrijk: 0
    finland: 0